import { DetectedAnomaly, Language, ShelfCalibration } from '../types';

export const DEFAULT_SHELF_IMAGE_URL = 'https://lh3.googleusercontent.com/aida-public/AB6AXuBzPTns1lwroCgu9pqzPlbk2dkUZ213Ldfq4DwksHwhzPfnmYBvmL7c-FysMzu2fGvI_6h5sHM9mZw4ABvAiyBW4p-4bme1xj6NMOLOLu-wwh7hYKZs2tWooib1VoHLu1I9bBU2TL_8k-DBHBTrNtbXLbkNRuIArojykTF0WFrTL8m5AaybxgJRXtsx_GZgrCzDpw26rtdnq2HWFGiWUeZ-ze78doCkNnjkLtjrppGuQocyV19TNWSxXg';

export const DEFAULT_SPLIT_Y: [number, number, number, number] = [0.295, 0.455, 0.618, 0.782];

export const DEFAULT_CALIBRATION: ShelfCalibration = {
  id: 'baseline-default',
  createdAt: Date.now(),
  imageDataUrl: DEFAULT_SHELF_IMAGE_URL,
  imageDimensions: { width: 1080, height: 1920 },
  splitYPercentages: DEFAULT_SPLIT_Y,
  tierLabels: [
    'Tier 1: 香氛/面霜',
    'Tier 2: 护肤精华',
    'Tier 3: 彩妆盘/粉底',
    'Tier 4: 香氛蜡烛/洗护',
  ],
};

export const INITIAL_MOCK_ANOMALIES: DetectedAnomaly[] = [
  {
    id: 'box-displaced-1',
    rowIndex: 1,
    type: 'MOVED',
    title: 'Drunk Elephant',
    displacementNote: '+8cm',
    score: 0.84,
    boundingBox: {
      x: 0.32,
      y: 0.37,
      width: 0.28,
      height: 0.09,
    },
    dismissed: false,
  },
  {
    id: 'box-displaced-2',
    rowIndex: 2,
    type: 'MOVED',
    title: 'NARS Palette',
    displacementNote: '倾斜 12°',
    score: 0.79,
    boundingBox: {
      x: 0.24,
      y: 0.54,
      width: 0.26,
      height: 0.08,
    },
    dismissed: false,
  },
  {
    id: 'box-missing',
    rowIndex: 3,
    type: 'MISSING',
    title: 'Aesop Balm (应放1件)',
    expectedCount: 1,
    confidence: 0.98,
    score: 0.95,
    boundingBox: {
      x: 0.34,
      y: 0.69,
      width: 0.21,
      height: 0.095,
    },
    dismissed: false,
  },
];

export const I18N = {
  cn: {
    appTitle: 'ShelfGuard 展架即时巡检',
    baselineEstablished: '基准图 (已建立)',
    baselineNotSet: '基准图 (未建立)',
    baselineTag: 'BASELINE',
    level: '水平',
    plumb: '倾角',
    tapShutterToScan: '轻按快门扫描展架陈列',
    ghostOpacity: '幽灵图透光率',
    ghost: 'Ghost',
    roiZone: 'ROI: 展架 4 排标定',
    resetBaseline: '重设基准图',
    resetConfirm: '确定要清除当前基准图并重新拍摄标定吗？',
    cancel: '取消',
    confirm: '确认',
    retake: '重拍',
    resetSplits: '重置分段',
    saveCalibration: '确认并保存基准',
    tierCalibration: '基准横梁标定',
    tierSubtitle: '四层货架层板边缘精密对准',
    tiersIdentified: '4 排已识别',
    dragHint: '拖动横线对齐层板上边缘，支持亚毫米自动磁吸',
    edgeSnapped: '边缘已吸附',
    auditResult: '展架巡检比对结果',
    complianceRate: '合规度',
    missingCount: '处缺失',
    displacedCount: '处变动',
    noMissing: '无缺失',
    noDisplaced: '无位移',
    pressHoldCompare: '长按对比基准原图',
    goldenBaseline: '基准标准图 (Standard Baseline)',
    toleranceSensitivity: '变动容差灵敏度 (Tolerance)',
    strict: '高 (严格)',
    normal: '中 (标准)',
    loose: '低 (宽松)',
    strictTolerance: '±2mm (严格)',
    normalTolerance: '±5mm (正常)',
    looseTolerance: '±12mm (宽松)',
    standardCapacity: '陈列标准位',
    actualOnShelf: '实测在架',
    displacementError: '位移误差',
    itemsUnit: '件',
    spotsUnit: '处',
    finishInspection: '确认并完成巡检',
    auditSyncSuccess: '巡检数据已归档并持久化保存！',
    exportReport: '导出巡检报告',
    auditHistory: '巡检历史记录',
    noHistory: '暂无历史巡检记录',
    installPwa: '安装至桌面',
    iosInstallGuide: 'iOS 用户请点击底栏分享按钮，选择“添加到主屏幕”',
    close: '关闭',
    scanning: '正在进行透视配准与差分分析...',
    useSampleFeed: '切换为演示货架画面',
    useRealCamera: '切换为物理摄像头',
    cameraPermissionDenied: '未能启动摄像头，已无缝切换至高精演示展架',
    switchCamera: '切换镜头',
    torchOn: '开启补光灯',
    torchOff: '关闭补光灯',
    processing: '正在分析展架差异，请稍候...',
    shutterLocked: '扫描进行中，请稍候',
  },
  en: {
    appTitle: 'ShelfGuard Planogram Audit',
    baselineEstablished: 'Baseline (Set)',
    baselineNotSet: 'Baseline (Empty)',
    baselineTag: 'BASELINE',
    level: 'LEVEL',
    plumb: 'PLUMB',
    tapShutterToScan: 'Tap shutter to scan shelf',
    ghostOpacity: 'Ghost Opacity',
    ghost: 'Ghost',
    roiZone: 'ROI: 4-Tier Planogram',
    resetBaseline: 'Reset Baseline',
    resetConfirm: 'Are you sure you want to clear current baseline and recalibrate?',
    cancel: 'Cancel',
    confirm: 'Confirm',
    retake: 'Retake',
    resetSplits: 'Reset Splits',
    saveCalibration: 'Save Calibration',
    tierCalibration: 'Shelf Plumb Calibration',
    tierSubtitle: 'Sub-millimeter Shelf Edge Alignment',
    tiersIdentified: '4 Tiers Locked',
    dragHint: 'Drag horizontal dividers to align shelf edges with magnetic snap',
    edgeSnapped: 'Edge Snapped',
    auditResult: 'Audit Inspection Results',
    complianceRate: 'Compliance',
    missingCount: 'Missing',
    displacedCount: 'Displaced',
    noMissing: 'Zero Missing',
    noDisplaced: 'Zero Displaced',
    pressHoldCompare: 'Press & hold to compare baseline',
    goldenBaseline: 'Golden Standard Baseline',
    toleranceSensitivity: 'Tolerance Sensitivity',
    strict: 'High (Strict)',
    normal: 'Medium (Normal)',
    loose: 'Low (Loose)',
    strictTolerance: '±2mm (Strict)',
    normalTolerance: '±5mm (Normal)',
    looseTolerance: '±12mm (Loose)',
    standardCapacity: 'Planogram Standard',
    actualOnShelf: 'Actual on Shelf',
    displacementError: 'Displaced Items',
    itemsUnit: 'items',
    spotsUnit: 'spots',
    finishInspection: 'Confirm & Finish Audit',
    auditSyncSuccess: 'Audit record successfully stored & synced!',
    exportReport: 'Export Audit Report',
    auditHistory: 'Audit History Logs',
    noHistory: 'No audit records yet',
    installPwa: 'Install PWA',
    iosInstallGuide: 'On iOS Safari, tap Share and select "Add to Home Screen"',
    close: 'Close',
    scanning: 'Aligning homography & computing differences...',
    useSampleFeed: 'Use Demo Shelf',
    useRealCamera: 'Use Camera',
    cameraPermissionDenied: 'Camera unavailable. Switched to high-res demo shelf.',
    switchCamera: 'Switch Camera',
    torchOn: 'Flashlight On',
    torchOff: 'Flashlight Off',
    processing: 'Analyzing shelf differences, please wait...',
    shutterLocked: 'Scan in progress, please wait',
  },
};
