import { DetectedAnomaly, Language, ShelfCalibration } from '../types';

/** Shelf carousel label chip. */
export function getShelfLabel(lang: Language, shelfIndex: number): string {
  const n = shelfIndex + 1;
  if (lang === 'cn') return `柜架 ${n}`;
  return lang === 'it' ? `Scaffale ${n}` : `Shelf ${n}`;
}

export const DEFAULT_CALIBRATION: ShelfCalibration = {
  id: 'baseline-default',
  createdAt: Date.now(),
  imageDataUrl: '',
  imageDimensions: { width: 1080, height: 1920 },
};

export const INITIAL_MOCK_ANOMALIES: DetectedAnomaly[] = [
  {
    id: 'box-displaced-1',
    type: 'MOVED',
    title: 'Drunk Elephant',
    displacementNote: '+8cm',
    score: 0.84,
    boundingBox: {
      x: 0.32,
      y: 0.37,
      width: 0.28,
      height: 0.09,
    },
    dismissed: false,
  },
  {
    id: 'box-displaced-2',
    type: 'MOVED',
    title: 'NARS Palette',
    displacementNote: 'inclinato 12°',
    score: 0.79,
    boundingBox: {
      x: 0.24,
      y: 0.54,
      width: 0.26,
      height: 0.08,
    },
    dismissed: false,
  },
  {
    id: 'box-missing',
    type: 'MISSING',
    title: 'Aesop Balm (atteso 1 pz)',
    expectedCount: 1,
    confidence: 0.98,
    score: 0.95,
    boundingBox: {
      x: 0.34,
      y: 0.69,
      width: 0.21,
      height: 0.095,
    },
    dismissed: false,
  },
];

export const I18N = {
  it: {
    appTitle: 'Online Market Ispezione Scaffali',
    baselineEstablished: 'Riferimento pronto',
    baselineNotSet: 'Nessun riferimento',
    baselineTag: 'RIFERIMENTO',
    level: 'IN BOLLA',
    plumb: 'INCLINAZIONE',
    tapShutterToScan: "Tocca l'otturatore per confrontare la foto",
    resetBaseline: 'Reimposta riferimento',
    resetConfirm: "Vuoi davvero cancellare la foto di riferimento e scattarne un'altra?",
    resetBaselineDescription:
      "La foto di riferimento viene confrontata per intero con ogni ispezione. Puoi caricarne una nuova.",
    uploadNewBaseline: 'Carica / scatta un nuovo riferimento',
    clearBaselineRecapture: 'Cancella il riferimento e riscatta',
    cancel: 'Annulla',
    confirm: 'Conferma',
    auditResult: "Risultato dell'ispezione",
    complianceRate: 'Conformità',
    missingCount: 'Mancanti',
    displacedCount: 'Spostati',
    noMissing: 'Nessun mancante',
    noDisplaced: 'Nessuno spostato',
    addedCount: 'Aggiunti',
    noAdded: 'Nessun aggiunto',
    pressHoldCompare: 'Tieni premuto per vedere il riferimento',
    expandPhoto: 'Ingrandisci a schermo intero',
    closeFullscreen: 'Chiudi',
    zoomIn: 'Ingrandisci',
    zoomOut: 'Riduci',
    goldenBaseline: 'Stai vedendo la foto di riferimento',
    toleranceSensitivity: 'Sensibilità (tolleranza)',
    strict: 'Alta (rigorosa)',
    normal: 'Media (standard)',
    loose: 'Bassa (permissiva)',
    strictTolerance: '±2mm (rigorosa)',
    normalTolerance: '±5mm (standard)',
    looseTolerance: '±12mm (permissiva)',
    toleranceValue: 'Tolleranza {n}',
    tolerancePresetStrict: 'Rigorosa (25)',
    tolerancePresetNormal: 'Standard (50)',
    tolerancePresetLoose: 'Permissiva (75)',
    confidenceThreshold: 'Soglia di affidabilità',
    confidenceThresholdHint: "Mostra solo le differenze con un'affidabilità pari o superiore",
    standardCapacity: 'Posizioni previste',
    actualOnShelf: 'Presenti a scaffale',
    displacementError: 'Spostamenti',
    itemsUnit: 'pz',
    spotsUnit: 'punti',
    finishInspection: "Conferma e concludi l'ispezione",
    auditSyncSuccess: 'Ispezione archiviata e salvata!',
    exportReport: 'Esporta il report',
    auditHistory: 'Storico ispezioni',
    noHistory: 'Nessuna ispezione registrata',
    installPwa: "Installa l'app",
    iosInstallGuide: 'Su iOS tocca il pulsante Condividi e scegli "Aggiungi alla schermata Home"',
    close: 'Chiudi',
    scanning: 'Allineamento e analisi delle differenze in corso...',
    cameraPermissionDenied: 'Accesso alla fotocamera negato',
    retryCamera: 'Riprova fotocamera',
    cameraErrorIosGuide:
      'Apri la pagina in Safari → Impostazioni → [Online Market] → consenti la Fotocamera, oppure reinstalla da Safari con "Aggiungi alla schermata Home".',
    offlineMode: 'Modalità offline · cache locale pronta',
    switchCamera: 'Passa alla fotocamera anteriore / posteriore',
    pickFromGallery: "Scegli la foto dell'ispezione dalla galleria",
    switchLens: 'Cambia obiettivo (es. grandangolo W)',
    torchOn: 'Accendi la torcia',
    torchOff: 'Spegni la torcia',
    zoomLevel: 'Zoom',
    processing: 'Analisi delle differenze in corso, attendere...',
    analysisFailed: "Analisi non riuscita, riprova lo scatto",
    framingMismatch:
      "L'orientamento o le proporzioni della foto non corrispondono al riferimento. Riscatta con lo stesso orientamento e obiettivo (es. grandangolo W)",
    lensMismatch:
      "Questa foto è stata scattata con un obiettivo diverso da quello del riferimento. Seleziona lo stesso obiettivo nella fotocamera di sistema (es. grandangolo W) e riscatta",
    shutterLocked: 'Scansione in corso, attendere',
    quotaExceededTitle: 'Memoria locale piena',
    quotaExceededGuide: 'Completa le ispezioni su altri scaffali o cancella parte dello storico, poi riprova.',
    orientationPermissionDenied: 'Accesso al sensore di orientamento negato',
    orientationErrorIosGuide:
      "Apri la pagina in Safari → Impostazioni → Safari → Accesso a movimento e orientamento, consenti e riprova.",
    retryOrientation: 'Riprova sensore',
    shelfCarouselLabel: 'Selezione scaffale',
    backToCamera: 'Torna alla fotocamera',
    exportReportToast: (rate: number) =>
      `Report generato: conformità ${rate}%, archiviato.`,
    captureScan: 'Scatta e analizza lo scaffale',
    viewPreviousAudit: "Vedi l'ultima ispezione",
    auditThumbnailAlt: 'Miniatura ispezione',
    missingBadgeShort: 'Mancante',
    addedBadgeShort: 'Aggiunto',
    movedBadgeShort: 'Spostato',
    firstBaselineHint: "Tocca l'otturatore per scattare il riferimento",
    enterFullscreen: 'Schermo intero',
    exitFullscreen: 'Esci da schermo intero',
  },
  cn: {
    appTitle: 'Online Market 展架即时巡检',
    baselineEstablished: '基准图 (已建立)',
    baselineNotSet: '基准图 (未建立)',
    baselineTag: 'BASELINE',
    level: '水平',
    plumb: '倾角',
    tapShutterToScan: '轻按快门对比照片',
    resetBaseline: '重设基准图',
    resetConfirm: '确定要清除当前基准图并重新拍摄标定吗？',
    resetBaselineDescription: '当前基准图用于每次巡检时的整图差分比对。您可以上传新拍摄的货架标准照。',
    uploadNewBaseline: '上传/拍照替换基准图',
    clearBaselineRecapture: '清除基准图并重新拍摄',
    cancel: '取消',
    confirm: '确认',
    auditResult: '展架巡检比对结果',
    complianceRate: '合规度',
    missingCount: '处缺失',
    displacedCount: '处变动',
    noMissing: '无缺失',
    noDisplaced: '无位移',
    addedCount: '处新增',
    noAdded: '无新增',
    pressHoldCompare: '长按对比基准原图',
    expandPhoto: '全屏放大查看',
    closeFullscreen: '关闭',
    zoomIn: '放大',
    zoomOut: '缩小',
    goldenBaseline: '正在显示基准原图',
    toleranceSensitivity: '变动容差灵敏度 (Tolerance)',
    strict: '高 (严格)',
    normal: '中 (标准)',
    loose: '低 (宽松)',
    strictTolerance: '±2mm (严格)',
    normalTolerance: '±5mm (正常)',
    looseTolerance: '±12mm (宽松)',
    toleranceValue: '容差 {n}',
    tolerancePresetStrict: '严格 (25)',
    tolerancePresetNormal: '标准 (50)',
    tolerancePresetLoose: '宽松 (75)',
    confidenceThreshold: '确认度阈值',
    confidenceThresholdHint: '只显示确认度不低于该值的差异',
    standardCapacity: '陈列标准位',
    actualOnShelf: '实测在架',
    displacementError: '位移误差',
    itemsUnit: '件',
    spotsUnit: '处',
    finishInspection: '确认并完成巡检',
    auditSyncSuccess: '巡检数据已归档并持久化保存！',
    exportReport: '导出巡检报告',
    auditHistory: '巡检历史记录',
    noHistory: '暂无历史巡检记录',
    installPwa: '安装至桌面',
    iosInstallGuide: 'iOS 用户请点击底栏分享按钮，选择“添加到主屏幕”',
    close: '关闭',
    scanning: '正在进行透视配准与差分分析...',
    cameraPermissionDenied: '无法访问摄像头',
    retryCamera: '重试摄像头',
    cameraErrorIosGuide:
      '请在 Safari 中打开本页 → 设置 → [Online Market] → 允许相机；或从 Safari「添加到主屏幕」重新安装。',
    offlineMode: '离线模式 · 本地缓存已就绪',
    switchCamera: '切换前/后置摄像头',
    pickFromGallery: '从相册选择巡检照片',
    switchLens: '切换镜头（如 W 广角）',
    torchOn: '开启补光灯',
    torchOff: '关闭补光灯',
    zoomLevel: '变焦',
    processing: '正在分析展架差异，请稍候...',
    analysisFailed: '分析失败，请重试拍摄',
    framingMismatch: '拍摄画面与基准图的方向/比例不一致，无法比对。请用与基准图相同的方向和镜头（如 W 广角）重拍',
    lensMismatch: '这张照片与基准图使用的镜头不同，无法比对。请在系统相机中切换到与基准图相同的镜头（如 W 广角）后重拍',
    shutterLocked: '扫描进行中，请稍候',
    quotaExceededTitle: '本地存储空间已满',
    quotaExceededGuide: '请先在其它货架完成巡检，或清除部分历史记录后再试。',
    orientationPermissionDenied: '无法访问设备方向传感器',
    orientationErrorIosGuide:
      '请在 Safari 中打开本页 → 设置 → Safari → 运动与方向访问，允许后返回重试。',
    retryOrientation: '重试方向权限',
    shelfCarouselLabel: '柜架选择',
    backToCamera: '返回相机',
    exportReportToast: (rate: number) =>
      `巡检报告已生成：合规度 ${rate}%，已归档。`,
    captureScan: '拍摄并扫描展架',
    viewPreviousAudit: '查看上次巡检',
    auditThumbnailAlt: '巡检缩略图',
    missingBadgeShort: '缺失',
    addedBadgeShort: '新增',
    movedBadgeShort: '移位',
    firstBaselineHint: '轻按快门拍摄基准图',
    enterFullscreen: '全屏',
    exitFullscreen: '退出全屏',
  },
  en: {
    appTitle: 'Online Market Planogram Audit',
    baselineEstablished: 'Baseline (Set)',
    baselineNotSet: 'Baseline (Empty)',
    baselineTag: 'BASELINE',
    level: 'LEVEL',
    plumb: 'PLUMB',
    tapShutterToScan: 'Tap the shutter to compare a photo',
    resetBaseline: 'Reset Baseline',
    resetConfirm: 'Are you sure you want to clear current baseline and recalibrate?',
    resetBaselineDescription:
      'The current baseline is used for whole-photo differential inspection. You can upload a new photo.',
    uploadNewBaseline: 'Upload / Snap New Baseline',
    clearBaselineRecapture: 'Clear baseline and recapture',
    cancel: 'Cancel',
    confirm: 'Confirm',
    auditResult: 'Audit Inspection Results',
    complianceRate: 'Compliance',
    missingCount: 'Missing',
    displacedCount: 'Displaced',
    noMissing: 'Zero Missing',
    noDisplaced: 'Zero Displaced',
    addedCount: 'Added',
    noAdded: 'Zero Added',
    pressHoldCompare: 'Press & hold to compare baseline',
    expandPhoto: 'Expand to full screen',
    closeFullscreen: 'Close',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    goldenBaseline: 'Showing the baseline photo',
    toleranceSensitivity: 'Tolerance Sensitivity',
    strict: 'High (Strict)',
    normal: 'Medium (Normal)',
    loose: 'Low (Loose)',
    strictTolerance: '±2mm (Strict)',
    normalTolerance: '±5mm (Normal)',
    looseTolerance: '±12mm (Loose)',
    toleranceValue: 'Tolerance {n}',
    tolerancePresetStrict: 'Strict (25)',
    tolerancePresetNormal: 'Normal (50)',
    tolerancePresetLoose: 'Loose (75)',
    confidenceThreshold: 'Confidence threshold',
    confidenceThresholdHint: 'Only differences at or above this confidence are shown',
    standardCapacity: 'Planogram Standard',
    actualOnShelf: 'Actual on Shelf',
    displacementError: 'Displaced Items',
    itemsUnit: 'items',
    spotsUnit: 'spots',
    finishInspection: 'Confirm & Finish Audit',
    auditSyncSuccess: 'Audit record successfully stored & synced!',
    exportReport: 'Export Audit Report',
    auditHistory: 'Audit History Logs',
    noHistory: 'No audit records yet',
    installPwa: 'Install PWA',
    iosInstallGuide: 'On iOS Safari, tap Share and select "Add to Home Screen"',
    close: 'Close',
    scanning: 'Aligning homography & computing differences...',
    cameraPermissionDenied: 'Camera access denied',
    retryCamera: 'Retry camera',
    cameraErrorIosGuide:
      'Open in Safari → Settings → [Online Market] → allow Camera, or reinstall via Safari Add to Home Screen.',
    offlineMode: 'Offline mode · Local cache ready',
    switchCamera: 'Switch front / rear camera',
    pickFromGallery: 'Choose inspection photo from library',
    switchLens: 'Switch lens (e.g. ultra-wide)',
    torchOn: 'Flashlight On',
    torchOff: 'Flashlight Off',
    zoomLevel: 'Zoom',
    processing: 'Analyzing shelf differences, please wait...',
    analysisFailed: 'Analysis failed — tap shutter to retry',
    framingMismatch: 'This photo does not match the baseline orientation/aspect ratio. Retake it with the same orientation and lens (e.g. W ultra-wide)',
    lensMismatch: 'This photo was taken with a different lens than the baseline. Switch the system camera to the same lens (e.g. W ultra-wide) and retake',
    shutterLocked: 'Scan in progress, please wait',
    quotaExceededTitle: 'Local storage is full',
    quotaExceededGuide:
      'Try completing audits on other shelves or clearing old history records, then retry.',
    orientationPermissionDenied: 'Motion sensor access denied',
    orientationErrorIosGuide:
      'Open in Safari → Settings → Safari → Motion & Orientation Access, then return and retry.',
    retryOrientation: 'Retry orientation',
    shelfCarouselLabel: 'Shelf selection',
    backToCamera: 'Back to Camera',
    exportReportToast: (rate: number) =>
      `Report exported: Compliance ${rate}%, saved.`,
    captureScan: 'Capture & Scan Planogram',
    viewPreviousAudit: 'View previous shelf audit',
    auditThumbnailAlt: 'Audit thumbnail',
    missingBadgeShort: 'Missing',
    addedBadgeShort: 'Added',
    movedBadgeShort: 'Moved',
    firstBaselineHint: 'Tap the shutter to take the baseline',
    enterFullscreen: 'Full screen',
    exitFullscreen: 'Exit full screen',
  },
};
