import { DetectedAnomaly, Language, ShelfCalibration } from '../types';

/** Shelf carousel label chip. */
export function getShelfLabel(lang: Language, shelfIndex: number): string {
  const n = shelfIndex + 1;
  return lang === 'it' ? `Scaffale ${n}` : `Shelf ${n}`;
}

export const DEFAULT_CALIBRATION: ShelfCalibration = {
  id: 'baseline-default',
  createdAt: Date.now(),
  imageDataUrl: '',
  imageDimensions: { width: 1080, height: 1920 },
};

export const INITIAL_MOCK_ANOMALIES: DetectedAnomaly[] = [
  {
    id: 'box-displaced-1',
    type: 'MOVED',
    title: 'Drunk Elephant',
    displacementNote: '+8cm',
    score: 0.84,
    boundingBox: {
      x: 0.32,
      y: 0.37,
      width: 0.28,
      height: 0.09,
    },
    dismissed: false,
  },
  {
    id: 'box-displaced-2',
    type: 'MOVED',
    title: 'NARS Palette',
    displacementNote: 'inclinato 12°',
    score: 0.79,
    boundingBox: {
      x: 0.24,
      y: 0.54,
      width: 0.26,
      height: 0.08,
    },
    dismissed: false,
  },
  {
    id: 'box-missing',
    type: 'MISSING',
    title: 'Aesop Balm (atteso 1 pz)',
    expectedCount: 1,
    confidence: 0.98,
    score: 0.95,
    boundingBox: {
      x: 0.34,
      y: 0.69,
      width: 0.21,
      height: 0.095,
    },
    dismissed: false,
  },
];

export const I18N = {
  it: {
    appTitle: 'ShelfGuard Ispezione Scaffali',
    baselineEstablished: 'Riferimento pronto',
    baselineNotSet: 'Nessun riferimento',
    baselineTag: 'RIFERIMENTO',
    level: 'IN BOLLA',
    plumb: 'INCLINAZIONE',
    tapShutterToScan: "Tocca l'otturatore per scansionare lo scaffale",
    resetBaseline: 'Reimposta riferimento',
    resetConfirm: "Vuoi davvero cancellare la foto di riferimento e scattarne un'altra?",
    resetBaselineDescription:
      "La foto di riferimento viene confrontata per intero con ogni ispezione. Puoi caricarne una nuova.",
    uploadNewBaseline: 'Carica / scatta un nuovo riferimento',
    clearBaselineRecapture: 'Cancella il riferimento e riscatta',
    cancel: 'Annulla',
    confirm: 'Conferma',
    auditResult: "Risultato dell'ispezione",
    complianceRate: 'Conformità',
    missingCount: 'Mancanti',
    displacedCount: 'Spostati',
    noMissing: 'Nessun mancante',
    noDisplaced: 'Nessuno spostato',
    addedCount: 'Aggiunti',
    noAdded: 'Nessun aggiunto',
    pressHoldCompare: 'Tieni premuto per vedere il riferimento',
    goldenBaseline: 'Stai vedendo la foto di riferimento',
    toleranceSensitivity: 'Sensibilità (tolleranza)',
    strict: 'Alta (rigorosa)',
    normal: 'Media (standard)',
    loose: 'Bassa (permissiva)',
    strictTolerance: '±2mm (rigorosa)',
    normalTolerance: '±5mm (standard)',
    looseTolerance: '±12mm (permissiva)',
    toleranceValue: 'Tolleranza {n}',
    tolerancePresetStrict: 'Rigorosa (25)',
    tolerancePresetNormal: 'Standard (50)',
    tolerancePresetLoose: 'Permissiva (75)',
    confidenceThreshold: 'Soglia di affidabilità',
    confidenceThresholdHint: "Mostra solo le differenze con un'affidabilità pari o superiore",
    standardCapacity: 'Posizioni previste',
    actualOnShelf: 'Presenti a scaffale',
    displacementError: 'Spostamenti',
    itemsUnit: 'pz',
    spotsUnit: 'punti',
    finishInspection: "Conferma e concludi l'ispezione",
    auditSyncSuccess: 'Ispezione archiviata e salvata!',
    exportReport: 'Esporta il report',
    auditHistory: 'Storico ispezioni',
    noHistory: 'Nessuna ispezione registrata',
    installPwa: "Installa l'app",
    iosInstallGuide: 'Su iOS tocca il pulsante Condividi e scegli "Aggiungi alla schermata Home"',
    close: 'Chiudi',
    scanning: 'Allineamento e analisi delle differenze in corso...',
    cameraPermissionDenied: 'Accesso alla fotocamera negato',
    retryCamera: 'Riprova fotocamera',
    cameraErrorIosGuide:
      'Apri la pagina in Safari → Impostazioni → [ShelfGuard] → consenti la Fotocamera, oppure reinstalla da Safari con "Aggiungi alla schermata Home".',
    offlineMode: 'Modalità offline · cache locale pronta',
    switchCamera: 'Passa alla fotocamera anteriore / posteriore',
    pickFromGallery: "Scegli la foto dell'ispezione dalla galleria",
    switchLens: 'Cambia obiettivo (es. grandangolo W)',
    torchOn: 'Accendi la torcia',
    torchOff: 'Spegni la torcia',
    zoomLevel: 'Zoom',
    processing: 'Analisi delle differenze in corso, attendere...',
    analysisFailed: "Analisi non riuscita, riprova lo scatto",
    framingMismatch:
      "L'orientamento o le proporzioni della foto non corrispondono al riferimento. Riscatta con lo stesso orientamento e obiettivo (es. grandangolo W)",
    lensMismatch:
      "Questa foto è stata scattata con un obiettivo diverso da quello del riferimento. Seleziona lo stesso obiettivo nella fotocamera di sistema (es. grandangolo W) e riscatta",
    nativeCaptureHint:
      "Il riferimento è stato scattato con la fotocamera di sistema · l'otturatore la apre: scegli lo stesso obiettivo (es. grandangolo W)",
    shutterLocked: 'Scansione in corso, attendere',
    quotaExceededTitle: 'Memoria locale piena',
    quotaExceededGuide: 'Completa le ispezioni su altri scaffali o cancella parte dello storico, poi riprova.',
    orientationPermissionDenied: 'Accesso al sensore di orientamento negato',
    orientationErrorIosGuide:
      "Apri la pagina in Safari → Impostazioni → Safari → Accesso a movimento e orientamento, consenti e riprova.",
    retryOrientation: 'Riprova sensore',
    shelfCarouselLabel: 'Selezione scaffale',
    backToCamera: 'Torna alla fotocamera',
    exportReportToast: (rate: number) =>
      `Report generato: conformità ${rate}%, archiviato.`,
    captureScan: 'Scatta e analizza lo scaffale',
    viewPreviousAudit: "Vedi l'ultima ispezione",
    auditThumbnailAlt: 'Miniatura ispezione',
    missingBadgeShort: 'Mancante',
    addedBadgeShort: 'Aggiunto',
    movedBadgeShort: 'Spostato',
    enterFullscreen: 'Schermo intero',
    exitFullscreen: 'Esci da schermo intero',
  },
  en: {
    appTitle: 'ShelfGuard Planogram Audit',
    baselineEstablished: 'Baseline (Set)',
    baselineNotSet: 'Baseline (Empty)',
    baselineTag: 'BASELINE',
    level: 'LEVEL',
    plumb: 'PLUMB',
    tapShutterToScan: 'Tap shutter to scan shelf',
    resetBaseline: 'Reset Baseline',
    resetConfirm: 'Are you sure you want to clear current baseline and recalibrate?',
    resetBaselineDescription:
      'The current baseline is used for whole-photo differential inspection. You can upload a new photo.',
    uploadNewBaseline: 'Upload / Snap New Baseline',
    clearBaselineRecapture: 'Clear baseline and recapture',
    cancel: 'Cancel',
    confirm: 'Confirm',
    auditResult: 'Audit Inspection Results',
    complianceRate: 'Compliance',
    missingCount: 'Missing',
    displacedCount: 'Displaced',
    noMissing: 'Zero Missing',
    noDisplaced: 'Zero Displaced',
    addedCount: 'Added',
    noAdded: 'Zero Added',
    pressHoldCompare: 'Press & hold to compare baseline',
    goldenBaseline: 'Showing the baseline photo',
    toleranceSensitivity: 'Tolerance Sensitivity',
    strict: 'High (Strict)',
    normal: 'Medium (Normal)',
    loose: 'Low (Loose)',
    strictTolerance: '±2mm (Strict)',
    normalTolerance: '±5mm (Normal)',
    looseTolerance: '±12mm (Loose)',
    toleranceValue: 'Tolerance {n}',
    tolerancePresetStrict: 'Strict (25)',
    tolerancePresetNormal: 'Normal (50)',
    tolerancePresetLoose: 'Loose (75)',
    confidenceThreshold: 'Confidence threshold',
    confidenceThresholdHint: 'Only differences at or above this confidence are shown',
    standardCapacity: 'Planogram Standard',
    actualOnShelf: 'Actual on Shelf',
    displacementError: 'Displaced Items',
    itemsUnit: 'items',
    spotsUnit: 'spots',
    finishInspection: 'Confirm & Finish Audit',
    auditSyncSuccess: 'Audit record successfully stored & synced!',
    exportReport: 'Export Audit Report',
    auditHistory: 'Audit History Logs',
    noHistory: 'No audit records yet',
    installPwa: 'Install PWA',
    iosInstallGuide: 'On iOS Safari, tap Share and select "Add to Home Screen"',
    close: 'Close',
    scanning: 'Aligning homography & computing differences...',
    cameraPermissionDenied: 'Camera access denied',
    retryCamera: 'Retry camera',
    cameraErrorIosGuide:
      'Open in Safari → Settings → [ShelfGuard] → allow Camera, or reinstall via Safari Add to Home Screen.',
    offlineMode: 'Offline mode · Local cache ready',
    switchCamera: 'Switch front / rear camera',
    pickFromGallery: 'Choose inspection photo from library',
    switchLens: 'Switch lens (e.g. ultra-wide)',
    torchOn: 'Flashlight On',
    torchOff: 'Flashlight Off',
    zoomLevel: 'Zoom',
    processing: 'Analyzing shelf differences, please wait...',
    analysisFailed: 'Analysis failed — tap shutter to retry',
    framingMismatch: 'This photo does not match the baseline orientation/aspect ratio. Retake it with the same orientation and lens (e.g. W ultra-wide)',
    lensMismatch: 'This photo was taken with a different lens than the baseline. Switch the system camera to the same lens (e.g. W ultra-wide) and retake',
    nativeCaptureHint: 'Baseline was taken with the system camera · the shutter opens it — pick the same lens (e.g. W ultra-wide)',
    shutterLocked: 'Scan in progress, please wait',
    quotaExceededTitle: 'Local storage is full',
    quotaExceededGuide:
      'Try completing audits on other shelves or clearing old history records, then retry.',
    orientationPermissionDenied: 'Motion sensor access denied',
    orientationErrorIosGuide:
      'Open in Safari → Settings → Safari → Motion & Orientation Access, then return and retry.',
    retryOrientation: 'Retry orientation',
    shelfCarouselLabel: 'Shelf selection',
    backToCamera: 'Back to Camera',
    exportReportToast: (rate: number) =>
      `Report exported: Compliance ${rate}%, saved.`,
    captureScan: 'Capture & Scan Planogram',
    viewPreviousAudit: 'View previous shelf audit',
    auditThumbnailAlt: 'Audit thumbnail',
    missingBadgeShort: 'Missing',
    addedBadgeShort: 'Added',
    movedBadgeShort: 'Moved',
    enterFullscreen: 'Full screen',
    exitFullscreen: 'Exit full screen',
  },
};
